### ISSUE TITLE
File block warning and missing DE43 breakdown

### ISSUE THREAD

**Issue by aljamalay** [adelosa/mciutil#43]
First, thank you for the great library. 

This is not an issue it is just a kind request of an enhancement, unfortintly I am not a python developer to handle it.

Is it possible to extract the csv file from IPM even if it contain a corrupted row or transaction for investigation purposes.

Thank you again.
Abdullah

**Comment by adelosa** [comment]
Abdullah, happy to assist but you will need to assist me in understanding the type of corruption you are wanting to handle. Are you able to construct an example file that causes the issue you are experiencing.. If not, any details about the types of corruptions you are experiencing would assist me in enhancing the app.

**Comment by aljamalay** [comment]
Dear Anthony, Thank you for your reply.

In one of my cases, I have one transaction in the file with ICC_DATA (159 charector) length less than expected, and when I tried to convert the file to CSV using mideu extract command I got this error message: 
2018-10-23 08:42:09,223:mciutil.mciutil:41:WARNING:File may not be in 1014 blocked format - found unusual EOB marker b'\x00\x00', usually x'40'x'40'
Consider using --no1014blocking option if file is VBS format
Traceback (most recent call last):
  File "mideu-script.py", line 11, in <module>
    load_entry_point('mciutil==0.5.0', 'console_scripts', 'mideu')()
  File "mciutil-0.5.0-py3.7.egg\mciutil\cli\mideu.py", line 27, in cli_entry
    _main(args)
  File "\mciutil\cli\mideu.py", line 53, in _main
    args.func(args)
  File "\mciutil\cli\extract.py", line 53, in extract_command
    ) for record in input_file
  File "\mciutil\cli\extract.py", line 53, in <listcomp>
    ) for record in input_file
  File "\mciutil\mciutil.py", line 299, in get_message_elements
    source_format)
  File "\mciutil\mciutil.py", line 339, in _process_element
    field_length = int(field_length_string)
ValueError: invalid literal for int() with base 10: b''

On another case, while using the same command the application is not adding the DE43 subtypes to the CSV file after converting it from IPM. I tried more than one file and most of them are accepted files. 

I am sorry that I can't share the files because of confidentiality reasons.

Thank you for your support.

**Comment by adelosa** [comment]
On the warning __"unusual EOB marker b'\x00\x00', usually x'40'x'40'"__
That warning was put in place to detect incorrect format and encoding issues..
The primary issue is that your file has not been blocked correctly in 1014 format. It could be the file is actually just VBS, in which case use the --no1014blocking option. Is your file EBCDIC or ASCII?
See https://mciutil.readthedocs.io/en/stable/usage.html#blocked-file-format which describes the expected 1014 format and https://mciutil.readthedocs.io/en/stable/usage.html#vbs-file-format for VBS format. 
Have a look at the file in question to see which one you are working with. If it's not one of these, let me know what it looks like.
In my experience, most length issues like the one you describe are actually related to the wrong options used (ASCII/EBCDIC encoding or format vbs or 1014) The other issue is the file has gone through some EBCDIC to ASCII conversion which will completely corrupt the file. You must have as binary version of the file.

On the missing DE43 breakdown.. This is probably caused by the format of the DE43 field not matching the REGEX expression that performs the breakdown.
```
de43_regex = (
        r"(?P<DE43_NAME>.+?) *\\(?P<DE43_ADDRESS>.+?) *\\(?P<DE43_SUBURB>.+?) *\\"
        r"(?P<DE43_POSTCODE>\S{4,10}) *(?P<DE43_STATE>.{3})(?P<DE43_COUNTRY>.{3})"
    )
```
If it does not match this, then it returns empty and you will not see the breakdown. If possible, can you send me the DE43 fields that you are having issues with so I can check against the above pattern and amend if necessary. Otherwise, suggest an alternative pattern for matching the elements in the DE43 field.

**Comment by adelosa** [comment]
Closing as no response so assuming you worked it out.
